# Generated by Django 4.1.5 on 2023-02-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
